stages:
  - build
  - test
  - deploy

frontend_build_job:
  stage: build
  image: node:latest
  script:
    - cd ./cra-frontend
    - echo "Start building App"
    - npm install
    - CI=false npm run build
    - echo "Build successfully!"
  artifacts:
    paths:
      - cra-frontend/build/

test-frontend: 
  stage: test   
  script:
    - echo "Running unit tests...."

frontend_deploy_job:
  stage: deploy
  image: python:latest
  script:
    - echo "Deploying App"
    - pip3 install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync ./cra-frontend/build s3://$S3_BUCKET_NAME --delete
